MAP = {
    'Done': 'passed',
    'Backlog': 'untestable',
    'Rejected': 'failed',
    'Selected for Dev': 'untestable',
    'Code Review': 'untestable',
    'In Progress': 'in progress',
    'UAT': 'in progress',
    'Delete': 'failed',
    'Not Doing': 'untestable',
    'Released': 'passed',
    'Tier 1': 'monitoring',
    'Tier 2': 'monitoring',
    'Tier 3': 'monitoring',
}
